main: com.tealcube.minecraft.bukkit.facecore.FacecorePlugin
version: ${project.version}-${git.commit.id.abbrev}
name: Facecore
api-version: 1.16
load: STARTUP
softdepend:
  - WorldGuard
  - PlaceholderAPI
  - DiscordSRV
  - LibsDisguises
  - ProtocolLib
