main: info.faceland.FacecorePlugin
name: ${project.build.name}
version: ${project.build.version}
author: ToppleTheNun
depend: [ProtocolLib]

commands:
  soundtest:
    aliases: [st]
  enchclear:
    aliases: [ec]

permissions:
  facecore.command.soundtest:
    default: op
  facecore.command.enchclear:
    default: op